name: free_ai_rock
description: An Android AI developer toolkit
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stability_image_generation: ^1.0.0
  edge_gen_ai: ^0.1.1
  nanobananapro: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
